services:
  timestream-prometheus-connector:
    container_name: connector
    build: ..
    ports:
      - "9201:9201"
    command:
      - --default-database=${DEFAULT_DATABASE:-DevPrometheusDatabase}
      - --default-table=${DEFAULT_TABLE:-DevPrometheusMetricsTable}
      - --region=${AWS_REGION:-us-west-2}
      - --log.level=debug
      - --read-base-endpoint=https://query-cell1.timestream.us-west-2.amazonaws.com
      - --write-base-endpoint=https://ingest-cell1.timestream.us-west-2.amazonaws.com
    environment:
      AWS_ENABLE_ENDPOINT_DISCOVERY: false
    networks:
      - aws_network

networks:
  aws_network:
    external: true
