services:
  timestream-prometheus-connector:
    container_name: connector
    image: fpimproving/amazon-timestream-connector-prometheus:privatelink
    ports:
      - "9201:9201"
    command:
      - --default-database=${DEFAULT_DATABASE:-DevPrometheusDatabase}
      - --default-table=${DEFAULT_TABLE:-DevPrometheusMetricsTable}
      - --region=${AWS_REGION:-us-west-2}
      - --log.level=debug
      - --read-base-endpoint=https://${QUERY_CELL:-query-cell1}.timestream.${AWS_REGION:-us-west-2}.amazonaws.com
      - --write-base-endpoint=https://${INGEST_CELL:-ingest-cell1}.timestream.${AWS_REGION:-us-west-2}.amazonaws.com
    environment:
      AWS_ENABLE_ENDPOINT_DISCOVERY: false
    networks:
      - aws_network

networks:
  aws_network:
    external: true
